### ISSUE TITLE
Add config option to not make the barcode a mandatory field

### ISSUE THREAD

**Issue by JornHendrickx** [LitusProject/Litus#251]
There are users who don't want to add barcodes to sale articles. For this the barcode field should not be mandatory. For the sake of convenience, a config option should also be created for this.

**Comment by MathijsC** [comment]
Already in the code:
https://github.com/LitusProject/Litus/blob/71919a9111f564c6f6ad617cd96287bfe565e777/module/CudiBundle/Form/Admin/Sale/Article/Add.php#L90
