### ISSUE TITLE
Is a mail send when using "Remove All" in bookings?

### ISSUE THREAD

**Issue by JornHendrickx** [LitusProject/Litus#253]
Does the system send a mail when you use the option Remove All in bookings? And when you use Expire All?

**Comment by MathijsC** [comment]
Remove all does not send an email:https://github.com/LitusProject/Litus/blob/71919a9111f564c6f6ad617cd96287bfe565e777/module/CudiBundle/Repository/Sale/Booking.php#L970
Expire all does send emails: https://github.com/LitusProject/Litus/blob/71919a9111f564c6f6ad617cd96287bfe565e777/module/CudiBundle/Repository/Sale/Booking.php#L1215
