### ISSUE TITLE
Restriction on amount

### ISSUE THREAD

**Issue by JornHendrickx** [LitusProject/Litus#258]
What happens when a sale article has a restriction on the amount (take 1) a customer can buy, and the article has expired. Can the customer order the article again?

**Comment by MathijsC** [comment]
All bookings in the current academic year with the status: Sold, Assigned or Booked are counted. If this value >= the restriction, the user is unable to make another booking. The following booking statusses are thus not taken in account: expired, canceled and returned.
https://github.com/LitusProject/Litus/blob/71919a9111f564c6f6ad617cd96287bfe565e777/module/CudiBundle/Entity/Sale/Article/Restriction/Amount.php#L75
